commonLabels:
  app.kubernetes.io/name: spotinst-cluster-controller

imageTags:
- name: spotinst/kubernetes-cluster-controller
  newTag: 1.0.30

namespace: kube-system

resources:
- certs-secret.yaml
- deployment.yaml
- rbac.yaml
